/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplication;

import crudclientrestful.Users;
import java.awt.event.ActionListener;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author hp
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    private Users user;
    public PanelPrincipal(Users user) {
        this.user=user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestanias = new javax.swing.JTabbedPane();
        panelLista = new javax.swing.JPanel();
        panelBoton = new javax.swing.JPanel();
        botonListar = new javax.swing.JButton();
        panelListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panelCrear = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        campoName = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        panelUpdate = new javax.swing.JPanel();
        panelSur = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        textPass = new javax.swing.JPasswordField();
        botonCancelarUp = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        panelEliminar = new javax.swing.JPanel();
        lbIdUser = new javax.swing.JLabel();
        campoIdDelete = new javax.swing.JTextField();
        labelVacio = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelLista.setLayout(new java.awt.BorderLayout());

        botonListar.setText("Listar Tabla");
        botonListar.setName("btnListar"); // NOI18N
        panelBoton.add(botonListar);

        panelLista.add(panelBoton, java.awt.BorderLayout.PAGE_START);

        panelListado.setLayout(new java.awt.BorderLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Email", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        panelListado.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelLista.add(panelListado, java.awt.BorderLayout.CENTER);

        pestanias.addTab("Listar usuarios", panelLista);

        panelCrear.setLayout(new java.awt.GridLayout(4, 2));

        labelName.setText("Nombre");
        panelCrear.add(labelName);
        panelCrear.add(campoName);

        labelEmail.setText("Email");
        panelCrear.add(labelEmail);
        panelCrear.add(campoEmail);

        labelPassword.setText("Password");
        panelCrear.add(labelPassword);
        panelCrear.add(pass);

        botonCancelar.setText("Cancelar");
        botonCancelar.setName("btnCancelar1"); // NOI18N
        panelCrear.add(botonCancelar);

        botonRegistrar.setText("Registrar");
        botonRegistrar.setName("btnRegistrar"); // NOI18N
        panelCrear.add(botonRegistrar);

        pestanias.addTab("Crear usuarios", panelCrear);

        panelUpdate.setLayout(new java.awt.BorderLayout());

        labelId.setText("Id del Usuario: ");
        panelSur.add(labelId);

        campoId.setColumns(5);
        panelSur.add(campoId);

        botonBuscar.setText("Buscar");
        botonBuscar.setName("btnBuscar"); // NOI18N
        panelSur.add(botonBuscar);

        panelUpdate.add(panelSur, java.awt.BorderLayout.PAGE_START);

        panelCentro.setLayout(new java.awt.GridLayout(4, 2));

        lbName.setText("Nombre");
        panelCentro.add(lbName);
        panelCentro.add(textName);

        lbEmail.setText("Email");
        panelCentro.add(lbEmail);
        panelCentro.add(textEmail);

        lbPassword.setText("Password");
        panelCentro.add(lbPassword);
        panelCentro.add(textPass);

        botonCancelarUp.setText("Cancelar");
        botonCancelarUp.setName("btnCancelar2"); // NOI18N
        panelCentro.add(botonCancelarUp);

        botonActualizar.setText("Actualizar");
        botonActualizar.setName("btnActualizar"); // NOI18N
        panelCentro.add(botonActualizar);

        panelUpdate.add(panelCentro, java.awt.BorderLayout.CENTER);

        pestanias.addTab("Actualizar Usuario", panelUpdate);

        panelEliminar.setLayout(new java.awt.GridLayout(2, 2));

        lbIdUser.setText("Id del usuario");
        panelEliminar.add(lbIdUser);
        panelEliminar.add(campoIdDelete);
        panelEliminar.add(labelVacio);

        botonEliminar.setText("Eliminar");
        botonEliminar.setName("btnEliminar"); // NOI18N
        panelEliminar.add(botonEliminar);

        pestanias.addTab("Eliminar Uusario", panelEliminar);

        add(pestanias, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCancelarUp;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonListar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoIdDelete;
    private javax.swing.JTextField campoName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelVacio;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbIdUser;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelListado;
    private javax.swing.JPanel panelSur;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTabbedPane pestanias;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textName;
    private javax.swing.JPasswordField textPass;
    // End of variables declaration//GEN-END:variables

    public JTextField getCampoEmail() {
        return campoEmail;
    }

    public void setCampoEmail(JTextField campoEmail) {
        this.campoEmail = campoEmail;
    }

    public JTextField getCampoId() {
        return campoId;
    }

    public void setCampoId(JTextField campoId) {
        this.campoId = campoId;
    }

    public JTextField getCampoIdDelete() {
        return campoIdDelete;
    }

    public void setCampoIdDelete(JTextField campoIdDelete) {
        this.campoIdDelete = campoIdDelete;
    }

    public JTextField getCampoName() {
        return campoName;
    }

    public void setCampoName(JTextField campoName) {
        this.campoName = campoName;
    }

    public JPasswordField getPass() {
        return pass;
    }

    public void setPass(JPasswordField pass) {
        this.pass = pass;
    }

    public JTable getTabla() {
        return tabla;
    }

    public void setTabla(JTable tabla) {
        this.tabla = tabla;
    }

    public JTextField getTextEmail() {
        return textEmail;
    }

    public void setTextEmail(JTextField textEmail) {
        this.textEmail = textEmail;
    }

    public JTextField getTextName() {
        return textName;
    }

    public void setTextName(JTextField textName) {
        this.textName = textName;
    }

    public JPasswordField getTextPass() {
        return textPass;
    }

    public void setTextPass(JPasswordField textPass) {
        this.textPass = textPass;
    }
    
    public void addEventos(ActionListener oyente){
        this.botonRegistrar.addActionListener(oyente);
        this.botonBuscar.addActionListener(oyente);
        this.botonActualizar.addActionListener(oyente);
        this.botonEliminar.addActionListener(oyente);
        this.botonCancelar.addActionListener(oyente);
        this.botonCancelarUp.addActionListener(oyente);
        this.botonListar.addActionListener(oyente);
    }
}
